name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint
    - name: Run ESLint On Front
      run: yarn lintfront
    - name: Run ESLint On Test
      run: yarn linttest
    - name: Run Mocha
      run: yarn test